apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vite-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhijeetdutta-1908/CICD_DevSecOps.git
    targetRevision: HEAD
    path: k8s 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true